// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zugpzdlgjvrhtlnbweqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Z3B6ZGxnanZyaHRsbmJ3ZXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzM1NTYsImV4cCI6MjA2NjkwOTU1Nn0.NzENdkuNnnPpXCfre_ZLd4bqqcr2AA5khaXrwynsZXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});